import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>New Metalion Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://www.metalion.world">New Metalion Project!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a
            href="https://www.liontravel.com"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>雄獅旅遊 &rarr;</h2>
            <p>跟團旅遊、機票、訂房、自由行、票券當地遊 .</p>
          </a>

          <a
            href="https://liontravel.qubic.market/products/147092"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>宙獅大旅社 &rarr;</h2>
            <p>打造華語旅遊Web3最佳社群</p>
          </a>

          <a
            href="https://www.metalion.world"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>宙獅 NFT 計劃 &rarr;</h2>
            <p>雄獅集團踏入元宇宙的第一站 .</p>
          </a>

          <a
            href="https://asiayo.com/zh-tw/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>AI_文本生成 &rarr;</h2>
            <p>生成各式各樣旅遊景點中英文介紹.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
